name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 📦 Copy project to server
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "~/python-service"

      # 🚀 SSH and run container
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            cd ~/python-service

            # Stop old container if exists
            docker stop python-service || true
            docker rm python-service || true

            # Build new image
            docker build -t python-service .

            # Run container
            docker run -d \
              --name python-service \
              -p 8000:8000 \
              -e DATABASE_URL="postgresql://admin:sumanth123@172.17.0.1:5432/placement" \
              python-service